[openai]
keys = [
"sk-aishouldbefreeanyway",
"sk-aishouldbefreeanyway",
"sk-aishouldbefreeanyway",
]
tokens = 2500
model = "text-davinci-003"
temperature = 0.8

[aibird]
protectedHosts = [
    {host = "yourirchost.com", ident = "nicktopluso", admin = true},
    {host = "yourirchost.com", ident = "nicktopluso", admin = false},
]
debug = false
useIpv6 = false

[networks.efnet]
nick = "aibird"
channels = ["#birdnest"]
enabled = true
throttle = 550
burst = 3
servers = [
    {host="irc.servercentral.net", port = 6667, ssl = false},
    {host="irc.efnet.nl", port = 6667, ssl = false}
]


[networks."tcpdirect irc"]
nick = "aibird"
channels = ["#birdnest", "#tcpdirect"]
enabled = true
throttle = 0
burst = 0
[[networks."tcpdirect irc".servers]]
host = "ircd.chat"
port = 6697
ssl = true
pass = ""


[stable-diffusion]
negativePrompt = "saturated, comic, cartoon, (anime:1.5), 3d, cgi, painting, deformed face, ((morbid)), ((mutilated)), [out of frame], extra fingers, mutated hands, ((poorly drawn face)), (((mutation))), (((deformed))), ((bad anatomy)), (((bad proportions))), ((extra limbs)), cloned face, (((disfigured))), extra limbs, gross proportions, (malformed limbs), ((missing arms)), ((missing legs)), (((extra arms))), (((extra legs))), (fused fingers), (too many fingers), (((long neck)))"
steps = 10
sampler = "DDIM"
restoreFace = true
cfgScale = 8
host = "http://127.0.0.1:7860"
width = 512
height = 640