[openai]
keys = [
"sk-aishouldbefreeanyway",
"sk-aishouldbefreeanyway",
"sk-aishouldbefreeanyway",
]
tokens = 2500
model = "text-davinci-003"
temperature = 0.8

[aibird]
admin = [
    {host = "yourirchost.com", ident = "nicktopluso"},
]
autoOps = [
    {host = "yourirchost.com", ident = "nicktopluso"},
]

[networks.efnet]
nick = "aibird"
channels = ["#birdnest"]
enabled = true
throttle = 550
burst = 3
servers = [
    {host="irc.servercentral.net", port = 6667, ssl = false},
    {host="irc.efnet.nl", port = 6667, ssl = false}
]


[networks."tcpdirect irc"]
nick = "aibird"
channels = ["#birdnest", "#tcpdirect"]
enabled = true
throttle = 0
burst = 0
[[networks."tcpdirect irc".servers]]
host = "ircd.chat"
port = 6697
ssl = true
pass = ""
